# Generated by Django 5.2.9 on 2026-06-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(max_length=150, verbose_name='Nombre del Cliente')),
                ('vertical', models.CharField(max_length=100, verbose_name='Vertical de Negocio')),
                ('estado_activo', models.BooleanField(default=True, verbose_name='¿Está Activo?')),
                ('fecha_alta', models.DateField(verbose_name='Fecha de Alta')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': '[cat].[Cliente]',
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_pais', models.CharField(max_length=100, verbose_name='Nombre del País')),
                ('codigo_pais', models.CharField(max_length=5, verbose_name='Código ISO (Ej: CL, PE)')),
                ('estado_activo', models.BooleanField(default=True, verbose_name='¿Activo?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'País',
                'verbose_name_plural': 'Países',
                'db_table': '[cat].[Pais]',
            },
        ),
    ]
