# Generated by Django 5.2.9 on 2026-06-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContractualMensual',
            fields=[
                ('id_contractual_mensual', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_periodo', models.DateField()),
                ('epa_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fcr_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sla_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('abandono_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('asa_segundos_objetivo', models.IntegerField(blank=True, null=True)),
                ('tmo_minutos_objetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acw_segundos_objetivo', models.IntegerField(blank=True, null=True)),
                ('agentes_objetivo', models.IntegerField(blank=True, null=True)),
                ('supervisores_objetivo', models.IntegerField(blank=True, null=True)),
                ('backoffice_objetivo', models.IntegerField(blank=True, null=True)),
                ('descripcion_servicio', models.TextField()),
                ('cobertura_horaria_multas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_contrato_modificacion', models.DateField(db_column='fecha_contrato_modificacion')),
            ],
            options={
                'db_table': 'kpi.ContractualMensual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ContractualMensualFS',
            fields=[
                ('id_contractual_mensual', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_periodo', models.DateField()),
                ('epa_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fcr_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sla_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('abandono_objetivo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('asa_segundos_objetivo', models.IntegerField(blank=True, null=True)),
                ('tmo_segundos_objetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acw_segundos_objetivo', models.IntegerField(blank=True, null=True)),
                ('agentes_objetivo', models.IntegerField(blank=True, null=True)),
                ('supervisores_objetivo', models.IntegerField(blank=True, null=True)),
                ('backoffice_objetivo', models.IntegerField(blank=True, null=True)),
                ('descripcion_servicio', models.TextField()),
                ('cobertura_horaria_multas', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_contrato_modificacion', models.DateField(db_column='fecha_contrato_modificacion')),
            ],
            options={
                'db_table': 'kpi.ContractualMensualFS',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Multa',
            fields=[
                ('id_multa', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_periodo', models.DateField()),
                ('servicio', models.CharField(choices=[('Field Service', 'Field Service'), ('Service Desk', 'Service Desk')], max_length=50, verbose_name='Tipo de Servicio')),
                ('monto_multa', models.DecimalField(decimal_places=2, max_digits=18)),
                ('descripcion_multa', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name': 'Multa',
                'verbose_name_plural': 'Multas',
                'db_table': '[kpi].[Multas]',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperacionMensual',
            fields=[
                ('id_operacion_mensual', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_periodo', models.DateField()),
                ('agentes_promedio', models.IntegerField()),
                ('supervisores_promedio', models.IntegerField()),
                ('backoffice_promedio', models.IntegerField()),
                ('tickets_humano', models.IntegerField()),
                ('hibridos_whatsapp_bi', models.IntegerField()),
                ('porcentaje_digitalizacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tickets_digital', models.IntegerField()),
                ('ingresos_totales_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                ('costos_totales_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                ('codigo_moneda', models.CharField(default='USD', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'kpi.OperacionMensual',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OperacionMensualFS',
            fields=[
                ('id_operacion_mensual', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_periodo', models.DateField()),
                ('agentes_promedio', models.IntegerField()),
                ('supervisores_promedio', models.IntegerField()),
                ('backoffice_promedio', models.IntegerField()),
                ('tickets_humano', models.IntegerField()),
                ('hibridos_whatsapp_bi', models.IntegerField()),
                ('porcentaje_digitalizacion', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tickets_digital', models.IntegerField()),
                ('ingresos_totales_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                ('costos_totales_usd', models.DecimalField(decimal_places=2, max_digits=18)),
                ('codigo_moneda', models.CharField(default='USD', max_length=3)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'kpi.OperacionMensualFS',
                'managed': False,
            },
        ),
    ]
