# Generated by Django 5.2.9 on 2026-06-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioApp',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_login', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('correo_corporativo', models.EmailField(max_length=200, unique=True)),
                ('es_administrador_global', models.BooleanField(default=False)),
                ('es_gerente_pais', models.BooleanField(db_column='es_gerente_pasi', default=False)),
                ('estado_activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='ultimo_acceso', null=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True)),
                ('fs', models.BooleanField(db_column='fs', default=False)),
                ('sd', models.BooleanField(db_column='sd', default=False)),
            ],
            options={
                'db_table': 'seg.UsuarioApp',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioClientePais',
            fields=[
                ('id', models.AutoField(db_column='id_usuario_cliente_pais', primary_key=True, serialize=False)),
                ('estado_activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'seg.UsuarioClientePais',
                'managed': False,
            },
        ),
    ]
